export const asyncTypes = Object.freeze({
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    CHANGE_TASK_ASYNC: 'CHANGE_TASK_ASYNC',
    // // unused
    // LIKE_TASK_ASYNC:       'LIKE_TASK_ASYNC',
    // UNLIKE_TASK_ASYNC:     'UNLIKE_TASK_ASYNC',
    // COMPLETE_TASK_ASYNC:   'COMPLETE_TASK_ASYNC',
    // UNCOMPLETE_TASK_ASYNC: 'UNCOMPLETE_TASK_ASYNC',
});
