export const asyncTypes = Object.freeze({
    FETCH_TASKS_ASYNC:   'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC:   'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC:   'REMOVE_TASK_ASYNC',
    CHANGE_TASK_ASYNC:   'CHANGE_TASK_ASYNC',
    COMPLETED_ALL_ASYNC: 'COMPLETED_ALL_ASYNC',
});
