export const asyncTypes = Object.freeze({
    FETCH_TASKS:           'FETCH_TASKS',
    CREATE_TASK_ASYNC:     'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC:     'REMOVE_TASK_ASYNC',
    LIKE_TASK_ASYNC:       'LIKE_TASK_ASYNC',
    UNLIKE_TASK_ASYNC:     'UNLIKE_TASK_ASYNC',
    COMPLETE_TASK_ASYNC:   'COMPLETE_TASK_ASYNC',
    UNCOMPLETE_TASK_ASYNC: 'UNCOMPLETE_TASK_ASYNC',
});
